name: test
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          key: test
      - name: Build database
        run: sqlite3 db.sqlite3 < create.sql
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          key: global-rust-cache
      - name: Clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          key: global-rust-cache
      - name: Check formatting
        run: cargo fmt --check

  results:
    permissions:
      pull-requests: write
    if: always()
    runs-on: ubuntu-latest
    needs: [build, clippy, fmt]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check Results
        run: |
          outcome='${{ toJSON(needs.*.result) }}'
          if [[ $(echo $outcome | jq -e 'all(. == "success")') != "true" ]]; then
            echo "Some required steps failed!";
            if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
              gh pr review ${{ github.event.number }} --request-changes --body "Some required steps failed!" || true;
            fi
            exit 1;
          elif [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            gh pr review ${{ github.event.number }} --approve --body "All CI jobs have passed. Approving." || true;
          fi
